### PR TITLE
[Documentation:InstructorUI] Student activity dashboard

### PR DESCRIPTION
**Pull request by AnoshanJ**
added documentation on student activity dashboard for instructor.

Closes https://github.com/Submitty/Submitty/issues/7603

### CODE REVIEW

**Comment by williamjallen** [comment]
Closes https://github.com/Submitty/Submitty/issues/7603

**Comment by AnoshanJ** [comment]
fixed PR title

**Comment by AnoshanJ** [comment]
request review

**Comment by AnoshanJ** [comment]
> request review

@williamjallen

**Comment by williamjallen** [comment]
These changes seem reasonable to me but it's up to @bmcutler for final approval

**Comment by AnoshanJ** [comment]
ok, thanks for the update

**Comment by AnoshanJ** [comment]
Kindly requesting a review @bmcutler

**Pull request merged**
