### PR TITLE
Include installation of ChromeDriver on Linux

### PR DESCRIPTION
**Pull request by xprilion**
Clear and concise documentation of the installation of ChromeDriver is not available on the website linked for ChromeDriver. I was using it for the first time and got fairly confused, having use an external blog to understand its installation process. It will help users to have it here. They keep changing the version numbers and there's no 'latest' release directory, thus the user may have to write the latest download's URL/version number himself.

### CODE REVIEW

**Comment by MasterOdin** [comment]
I think it's probably better to actually just remove the example installation lines for ChromeDriver and just leave it to the user to figure out the proper way to install it on their platform.

If we go this route, then we're sort of locking ourselves to either updating this page often as new versions of Chrome come out, or just have it fall way out of date and be essentially useless.

**Comment by xprilion** [comment]
@MasterOdin could we not provide it through the Submitty setup scripts? Maybe I can write a small patch for enabling getting the latest version!

**Comment by MasterOdin** [comment]
While I will actually probably make a script that does get and install the proper version of chromedriver for your version of chrome for Travis, this isn't really something I'd want to publicly advertise to end-users. I think it's also probably important that a user go to their website and read how ChromeDriver works (and versions supported, etc.) so that they get an idea of how that works and when they would need to update it.

**Comment by MasterOdin** [comment]
Thanks for this. I've updated the instructions to be something we don't have to touch to keep the version up to-date. We can mend the instructions further (or email upstream) if people find following https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection confusing to determine the appropriate ChromeDriver version (though it's a lot more sane than it used to be).

**Pull request merged**
