### PR TITLE
update docs to reference new install script

### PR DESCRIPTION
**Pull request by MasterOdin**
Docs update for Submitty/Submitty#4600

Does not look like we actually have anywhere in the docs explicitly for running the `install_submitty.sh` script.

### CODE REVIEW

**Comment by bmcutler** [comment]
I think you've missed a bunch:

https://submitty.org/sysadmin/update
https://submitty.org/sysadmin/worker_installation
https://submitty.org/sysadmin/version_notes/v19.08.03
https://submitty.org/developer/development_instructions

probably more

**Comment by MasterOdin** [comment]
Ugh, you are right. It looks like after I did my first change, VSCode switched my search term to `SUBMITTY_INSTALL` and I did not realize it. Should have gotten everything properly this time around.

**Comment by bmcutler** [comment]
You've removed a lot of trailing spaces at the end of the line.
However, some of those double spaces are important for formatting markdown.

**Comment by bmcutler** [comment]
@MasterOdin 
nudge on my previous comment

**Comment by MasterOdin** [comment]
Yeah, that's a fair point, but given that Submitty/Submitty#4600 is closed, closing this as well.

**Pull request closed without merging**
